name: location
description: "Proyecto Flutter - AuditorÃ­a Geoespacial"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ğŸ”¹ GestiÃ³n de estado sin setState
  flutter_riverpod: ^2.5.0

  # ğŸ”¹ GPS eficiente
  geolocator: ^10.1.0

  # ğŸ”¹ Descarga de modelos desde servidor (lazy loading)
  http: ^1.2.0

  # ğŸ”¹ Guardar modelos en cache local
  path_provider: ^2.1.2

  # ğŸ”¹ OPCIONAL â†’ solo si vas a mostrar modelos 3D
  model_viewer_plus: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true